"""empty message

Revision ID: a772a7437b71
Revises: 
Create Date: 2024-11-08 17:51:07.849820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a772a7437b71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('current_job_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('linkedin_profile_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('job_titles_of_interest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_years_of_experience', sa.Integer(), nullable=True),
    sa.Column('education_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key_skills', sa.JSON(), nullable=True),
    sa.Column('general_salary_range', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preferred_salary_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('open_to_performance_based_compensation', sa.Boolean(), nullable=False),
    sa.Column('willing_to_negociate', sa.Boolean(), nullable=False),
    sa.Column('minimum_acceptable_salary', sa.Integer(), nullable=True),
    sa.Column('preferred_benefits', sa.JSON(), nullable=True),
    sa.Column('view_salary_expectations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hide_profile_from_current_employer', sa.Boolean(), nullable=False),
    sa.Column('industries_of_interest', sa.JSON(), nullable=True),
    sa.Column('job_type_preferences', sa.JSON(), nullable=True),
    sa.Column('actively_looking_for_new_job', sa.Boolean(), nullable=False),
    sa.Column('career_goals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('professional_development_areas', sa.JSON(), nullable=True),
    sa.Column('role_specific_salary_adjustments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interested_in_salary_benchmarks', sa.Boolean(), nullable=False),
    sa.Column('resume_upload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_letter_upload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_employer', sa.JSON(), nullable=True),
    sa.Column('job_alerts_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referral_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('client_profile',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headquarters_location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('primary_contact_person', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('primary_hiring_goals', sa.JSON(), nullable=True),
    sa.Column('preferred_job_locations', sa.JSON(), nullable=True),
    sa.Column('roles_of_interest', sa.JSON(), nullable=True),
    sa.Column('job_types', sa.JSON(), nullable=True),
    sa.Column('dashboard_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_specific_customization', sa.Boolean(), nullable=True),
    sa.Column('salary_benchmarking_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('candidate_viewing_preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('offer_optimization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enable_real_time_market_alerts', sa.Boolean(), nullable=False),
    sa.Column('enable_custom_reporting', sa.Boolean(), nullable=False),
    sa.Column('preferred_report_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('automated_updates', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('candidate_feedback_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invite_team_member', sa.JSON(), nullable=True),
    sa.Column('referral_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_super_user', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_demo',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', name='jobstatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_provider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_application',
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='applicationstatusenum'), nullable=True),
    sa.Column('salary_expectation', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profile.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application')
    op.drop_table('social_provider')
    op.drop_table('job')
    op.drop_table('request_demo')
    op.drop_table('client_profile')
    op.drop_table('candidate_profile')
    # ### end Alembic commands ###
